package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_repository",
    srcs = ["function_repository.cpp"],
    hdrs = ["function_repository.h"],
    deps = ["//src/function:function"],
)
