package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_ir_assembly_test",
    srcs = ["function_ir_assembly_test.cpp"],
    deps = [
        "//src/function_ir_assembly:function_ir_assembly",
        "@gtest//:gtest_main",
    ],
)
