package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_ir",
    srcs = ["function_ir.cpp"],
    hdrs = ["function_ir.h"],
    deps = ["//src/function_id:function_id"],
)
