package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_primitive_cpp_test",
    srcs = ["function_primitive_cpp_test.cpp"],
    deps = [
        "//src/function_primitive_cpp:function_primitive_cpp",
        "@gtest//:gtest_main",
    ],
)
