package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_ir_file_repository",
    srcs = ["function_ir_file_repository.cpp"],
    includes = ["."],
    hdrs = ["function_ir_file_repository.h"],
    deps = [
        "//src/function_ir:function_ir",
        "//src/function_ir_binary:function_ir_binary",
        "//src/typesystem:typesystem",
    ],
)
