package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_primitive_lang_test",
    srcs = ["function_primitive_lang_test.cpp"],
    deps = [
        "//src/function_primitive_lang:function_primitive_lang",
        "@gtest//:gtest_main",
    ],
)
