package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function",
    srcs = ["function.cpp"],
    hdrs = ["function.h"],
    deps = [
        "//src/function_ir:function_ir",
        "//src/typesystem:typesystem",
    ],
)
