package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_ir_file_repository_test",
    srcs = ["function_ir_file_repository_test.cpp"],
    includes = ["."],
    deps = [
        "//src/function_ir_file_repository:function_ir_file_repository",
        "//src/google_test:gtest_main",
    ],
)
