package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_compound_test",
    srcs = ["function_compound_test.cpp"],
    deps = [
        "//src/function_compound:function_compound",
        "@gtest//:gtest_main",
    ],
)
