package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_primitive_cpp",
    srcs = ["function_primitive_cpp.cpp"],
    hdrs = ["function_primitive_cpp.h"],
    deps = ["//src/function:function"],
)
