package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_primitive_lang",
    srcs = ["function_primitive_lang.cpp"],
    includes = ["."],
    hdrs = ["function_primitive_lang.h"],
    deps = ["//src/function:function"],
)
