package(default_visibility = ["//visibility:public"])

cc_test(
    name = "call_test",
    srcs = ["call_test.cpp"],
    includes = ["."],
    deps = [
        "//src/call:call",
        "//src/google_test:gtest_main",
    ],
)
