package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_call_repository_test",
    srcs = ["function_call_repository_test.cpp"],
    deps = [
        "//src/function_call_repository:function_call_repository",
        "//src/google_test:gtest_main",
    ],
)
