package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_alu",
    srcs = ["function_alu.cpp"],
    hdrs = ["function_alu.h"],
    deps = [
        "//src/function:function",
        "//src/typesystem:typesystem",
    ],
)
