package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_ir_binary_test",
    srcs = ["function_ir_binary_test.cpp"],
    deps = [
        "//src/function_ir_binary:function_ir_binary",
        "@gtest//:gtest_main",
    ],
)
