package(default_visibility = ["//visibility:public"])

cc_library(
    name = "typesystem_call",
    srcs = ["typesystem_call.cpp"],
    includes = ["."],
    hdrs = ["typesystem_call.h"],
    deps = [
        "//src/call:call",
        "//src/typesystem:typesystem",
    ],
)
