package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_visualizer_editor",
    srcs = ["function_visualizer_editor.cpp"],
    includes = ["."],
    hdrs = ["function_visualizer_editor.h"],
    deps = [
        "//src/imgui:imgui",
        "//src/rlImGui:rlImGui",
    ],
)
