package(default_visibility = ["//visibility:public"])

cc_test(
    name = "typesystem_test",
    srcs = ["typesystem_test.cpp"],
    deps = [
        "//src/typesystem:typesystem",
        "@gtest//:gtest_main",
    ],
)
