package(default_visibility = ["//visibility:public"])

cc_test(
    name = "typesystem_test",
    srcs = ["typesystem_test.cpp"],
    includes = ["."],
    deps = [
        "//src/typesystem:typesystem",
        "//src/google_test:gtest_main",
    ],
)
