package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_call_repository",
    srcs = ["function_call_repository.cpp"],
    hdrs = ["function_call_repository.h"],
    deps = [
        "//src/function:function",
        "//src/function_id:function_id",
    ],
)
