package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_alu_test",
    srcs = ["function_alu_test.cpp"],
    deps = [
        "//src/function_alu:function_alu",
        "@gtest//:gtest_main",
    ],
)
