package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_ir_binary",
    srcs = ["function_ir_binary.cpp"],
    hdrs = ["function_ir_binary.h"],
    deps = ["//src/function_ir:function_ir"],
)
