#ifndef M03GAGBHTFT23YHJWPP881TFMC_UUID_UUID_H
# define M03GAGBHTFT23YHJWPP881TFMC_UUID_UUID_H

# include <array>
# include <chrono>
# include <span>
# include <format>
# include <string>
# include <cstdint>
# include <cstddef>

namespace m03gagbhtft23yhjwpp881tfmc_uuid {

/**
 * @brief Owns a 16-byte RFC 9562 UUID.
 */
class uuid {
public:
    /**
     * @brief Constructs a uuid from bytes.
     *
     * @param bytes The 16 UUID bytes in network byte order.
     *
     * @throws std::invalid_argument on invalid input.
     */
    explicit uuid(std::span<const std::byte> bytes);

    /**
     * @brief Generates a uuid.
     *
     * UUIDv7 values generated by this process are byte-wise sortable in generation order.
     *
     * @param version The UUID version to generate. Must be between 1 and 8.
     * @return A generated uuid.
     *
     * @throws std::invalid_argument on invalid input.
     * @throws std::runtime_error on generation failure.
     */
    static uuid generate(unsigned version);

    /**
     * @brief Returns a view over the stored bytes.
     *
     * @return A non-owning view over the 16 UUID bytes.
     */
    std::span<const std::byte> bytes() const noexcept;

    /**
     * @brief Returns the UUID version.
     *
     * @return The UUID version encoded in the stored bytes.
     */
    unsigned version() const noexcept;

    /**
     * @brief Returns the UUID timestamp.
     * Only valid for UUID versions that encode a timestamp.
     *
     * @return The UUID Unix millisecond timestamp.
     *
     * @throws std::logic_error if the UUID version has no supported timestamp representation.
     * @throws std::range_error if the timestamp is not representable.
     */
    std::chrono::system_clock::time_point timestamp() const;

private:
    explicit uuid(std::array<std::byte, 16> bytes);

    static uuid generate_uuidv7();
    std::chrono::system_clock::time_point timestamp_uuidv7() const;

private:
    std::array<std::byte, 16> m_bytes;
};

} // namespace m03gagbhtft23yhjwpp881tfmc_uuid

namespace std {

template <>
struct formatter<m03gagbhtft23yhjwpp881tfmc_uuid::uuid> {
    constexpr auto parse(std::format_parse_context& ctx) {
        auto it = ctx.begin();

        if (it != ctx.end() && *it != '}') {
            throw std::format_error("invalid uuid format specifier");
        }

        return it;
    }

    auto format(const m03gagbhtft23yhjwpp881tfmc_uuid::uuid& uuid, auto& ctx) const {
        auto out = ctx.out();

        const auto bytes = uuid.bytes();
        for (std::size_t i = 0; i < bytes.size(); ++i) {
            if (i == 4 || i == 6 || i == 8 || i == 10) {
                out = std::format_to(out, "{}", '-');
            }
            out = std::format_to(out, "{:02x}", std::to_integer<uint32_t>(bytes[i]));
        }

        return out;
    }
};

} // namespace std

#endif // M03GAGBHTFT23YHJWPP881TFMC_UUID_UUID_H
