#ifndef M03GAGBHTFT23YHJWPP881TFMC_UUID_UUID_H
# define M03GAGBHTFT23YHJWPP881TFMC_UUID_UUID_H

# include <array>
# include <chrono>
# include <span>
# include <format>
# include <string>
# include <cstdint>
# include <cstddef>

namespace m03gagbhtft23yhjwpp881tfmc_uuid {

/**
 * @brief Owns a 16-byte RFC 9562 UUIDv7 with a Unix millisecond timestamp.
 *
 * Public construction accepts only version 7 with variant bits 0b10. The timestamp
 * field can exceed the range of system_clock even when construction succeeds.
 *
 * @code{.cpp}
 * #include <m03gagbhtft23yhjwpp881tfmc_uuid/uuid.h>
 *
 * #include <cassert>
 * #include <chrono>
 *
 * int main() {
 *     using m03gagbhtft23yhjwpp881tfmc_uuid::uuid;
 *     const auto generated_uuid = uuid::generate(7);
 *     const auto bytes = generated_uuid.bytes(); // Keep generated_uuid alive.
 *     const uuid copied_uuid(bytes); // Copies and validates all 16 bytes.
 *     const auto unix_millis = std::chrono::duration_cast<std::chrono::milliseconds>(
 *         copied_uuid.timestamp().time_since_epoch()
 *     ).count();
 *     assert(bytes.size() == 16);
 *     assert(copied_uuid.version() == 7);
 *     assert(0 <= unix_millis);
 * }
 * @endcode
 */
class uuid {
public:
    /**
     * @brief Copies and validates a UUIDv7 byte sequence.
     *
     * @param bytes The 16 readable UUID bytes in network byte order; no storage is borrowed.
     *
     * @throws std::invalid_argument If the byte count is not 16, the data pointer is
     * null, the high four bits of byte 6 are not 0b0111, or the high two bits of
     * byte 8 are not 0b10. Other UUID versions, including a nil UUID, are rejected.
     */
    explicit uuid(std::span<const std::byte> bytes);

    /**
     * @brief Generates a UUIDv7 ordered by its bytes within this process.
     *
     * UUIDv7 values generated by this process are byte-wise sortable in generation order.
     * Calls may run concurrently; ordering follows the generator's serialized state
     * updates, not necessarily call return order. Repeated or backward clock readings
     * retain the last timestamp and increment the random field.
     *
     * @param version The UUID version to generate. Must be 7.
     * @return A generated uuid.
     *
     * @throws std::invalid_argument If version is not 7.
     * @throws std::runtime_error If OS randomness fails, the system clock is outside
     * the UUIDv7 timestamp range, or the incrementing random field is exhausted.
     */
    static uuid generate(unsigned version);

    /**
     * @brief Borrows a read-only view over the 16 stored bytes in network byte order.
     *
     * @return A non-owning view over the 16 UUID bytes.
     * Keep this uuid alive while using the view; calling bytes() on a temporary
     * does not extend its lifetime. Assignment changes the bytes seen by an existing
     * view. Copying or moving a uuid does not make its views refer to the destination.
     */
    std::span<const std::byte> bytes() const noexcept;

    /**
     * @brief Returns the UUID version.
     *
     * @return 7 for every UUID accepted or generated by this API.
     */
    unsigned version() const noexcept;

    /**
     * @brief Converts the UUIDv7's 48-bit Unix millisecond field to a system_clock time point.
     *
     * @return The encoded timestamp, with millisecond precision, not the time of this call.
     *
     * @throws std::range_error If the timestamp is not representable by system_clock.
     * Byte construction validates version and variant but does not check this range.
     */
    std::chrono::system_clock::time_point timestamp() const;

private:
    explicit uuid(std::array<std::byte, 16> bytes);

    static uuid generate_uuidv7();
    std::chrono::system_clock::time_point timestamp_uuidv7() const;

private:
    std::array<std::byte, 16> m_bytes;
};

} // namespace m03gagbhtft23yhjwpp881tfmc_uuid

namespace std {

template <>
struct formatter<m03gagbhtft23yhjwpp881tfmc_uuid::uuid> {
    constexpr auto parse(std::format_parse_context& ctx) {
        auto it = ctx.begin();

        if (it != ctx.end() && *it != '}') {
            throw std::format_error("invalid uuid format specifier");
        }

        return it;
    }

    auto format(const m03gagbhtft23yhjwpp881tfmc_uuid::uuid& uuid, auto& ctx) const {
        auto out = ctx.out();

        const auto bytes = uuid.bytes();
        for (std::size_t i = 0; i < bytes.size(); ++i) {
            if (i == 4 || i == 6 || i == 8 || i == 10) {
                out = std::format_to(out, "{}", '-');
            }
            out = std::format_to(out, "{:02x}", std::to_integer<uint32_t>(bytes[i]));
        }

        return out;
    }
};

} // namespace std

#endif // M03GAGBHTFT23YHJWPP881TFMC_UUID_UUID_H
