package(default_visibility = ["//visibility:public"])

cc_test(
    name = "typesystem_call_test",
    srcs = ["typesystem_call_test.cpp"],
    deps = [
        "//src/typesystem_call:typesystem_call",
        "//src/google_test:gtest_main",
    ],
)
