package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_test",
    srcs = ["function_test.cpp"],
    deps = [
        "//src/function:function",
        "@gtest//:gtest_main",
    ],
)
