package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_ir_test",
    srcs = ["function_ir_test.cpp"],
    includes = ["."],
    deps = [
        "//src/function_ir:function_ir",
        "//src/google_test:gtest_main",
    ],
)
