package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_ir_assembly",
    srcs = ["function_ir_assembly.cpp"],
    includes = ["."],
    hdrs = ["function_ir_assembly.h"],
    deps = ["//src/function_ir:function_ir"],
)
