package(default_visibility = ["//visibility:public"])

cc_library(
    name = "function_compound",
    srcs = ["function_compound.cpp"],
    hdrs = ["function_compound.h"],
    deps = [
        "//src/function:function",
        "//src/function_id:function_id",
        "//src/typesystem:typesystem",
    ],
)
