package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_repository_test",
    srcs = ["function_repository_test.cpp"],
    deps = [
        "//src/function_repository:function_repository",
        "@gtest//:gtest_main",
    ],
)
