#ifndef M03GAGBHTFT23YHJWPP881TFMC_UUIDV7_UUIDV7_H
# define M03GAGBHTFT23YHJWPP881TFMC_UUIDV7_UUIDV7_H

# include <array>
# include <span>

# include <cstdint>

namespace uuidv7 {

class uuidv7 {
public:
    /**
     * Generates an RFC 9562 UUIDv7.
     *
     * UUIDs generated by this process are byte-wise sortable in generation order.
     */
    static uuidv7 generate();

    /**
     * Returns the 16-byte UUID representation.
     */
    std::span<const std::uint8_t> bytes() const;

private:
    explicit uuidv7(std::array<std::uint8_t, 16> bytes);

private:
    std::array<std::uint8_t, 16> m_bytes;
};

} // namespace uuidv7

#endif // M03GAGBHTFT23YHJWPP881TFMC_UUIDV7_UUIDV7_H
