package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_id_test",
    srcs = ["function_id_test.cpp"],
    includes = ["."],
    deps = [
        "//src/function_id:function_id",
        "//src/google_test:gtest_main",
    ],
)
