package(default_visibility = ["//visibility:public"])

cc_test(
    name = "function_id_test",
    srcs = ["function_id_test.cpp"],
    deps = [
        "//src/function_id:function_id",
        "@gtest//:gtest_main",
    ],
)
